// Code generated by MockGen. DO NOT EDIT.
// Source: ./windows/adapter/network_adapter.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNetworkAdapter is a mock of NetworkAdapter interface.
type MockNetworkAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkAdapterMockRecorder
}

// MockNetworkAdapterMockRecorder is the mock recorder for MockNetworkAdapter.
type MockNetworkAdapterMockRecorder struct {
	mock *MockNetworkAdapter
}

// NewMockNetworkAdapter creates a new mock instance.
func NewMockNetworkAdapter(ctrl *gomock.Controller) *MockNetworkAdapter {
	mock := &MockNetworkAdapter{ctrl: ctrl}
	mock.recorder = &MockNetworkAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkAdapter) EXPECT() *MockNetworkAdapterMockRecorder {
	return m.recorder
}

// GetAdapterNames mocks base method.
func (m *MockNetworkAdapter) GetAdapterNames() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdapterNames")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdapterNames indicates an expected call of GetAdapterNames.
func (mr *MockNetworkAdapterMockRecorder) GetAdapterNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdapterNames", reflect.TypeOf((*MockNetworkAdapter)(nil).GetAdapterNames))
}

// GetPriorityVLANTag mocks base method.
func (m *MockNetworkAdapter) GetPriorityVLANTag(adapterName string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriorityVLANTag", adapterName)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriorityVLANTag indicates an expected call of GetPriorityVLANTag.
func (mr *MockNetworkAdapterMockRecorder) GetPriorityVLANTag(adapterName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriorityVLANTag", reflect.TypeOf((*MockNetworkAdapter)(nil).GetPriorityVLANTag), adapterName)
}

// SetPriorityVLANTag mocks base method.
func (m *MockNetworkAdapter) SetPriorityVLANTag(adapterName string, value int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPriorityVLANTag", adapterName, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPriorityVLANTag indicates an expected call of SetPriorityVLANTag.
func (mr *MockNetworkAdapterMockRecorder) SetPriorityVLANTag(adapterName, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPriorityVLANTag", reflect.TypeOf((*MockNetworkAdapter)(nil).SetPriorityVLANTag), adapterName, value)
}
